### ISSUE TITLE
Broke FF45 Badly; Weirdness Opening Tabs

### ISSUE THREAD

**Issue by seascape** [char101/tabgroupsbtn#13]
I was using Tab Groups Button in tandem with Tab Groups, the add-on.

I went to setup a new FF45 profile, fresh install. Added all of my customary add-ons, 25 or so. Restarted FF and suddenly FF can no longer open new tabs when you click on things like Options or Add-ons in the hamburger menu. Typing into the address bar still works. Session Manager no longer restored the previous session.

Disabling add-ons one by one revealed Tab Groups Button to be the offender.

That is all the testing I've done, as I need to continue setting this up and can go on without TGB. It was a perfectly nice add-on when it previously worked, though.

**Comment by char101** [comment]
Open your [Browser Console](https://developer.mozilla.org/en/docs/Tools/Browser_Console), type `tabgroupsbtn` in the search box, then copy the lines here.

**Comment by seascape** [comment]
Hi Char101,

More info actually; may be a false alarm. The errors occurred again and this time it seemed to point to KeeFox. Just checked if that updated recently and introduced this problem, but no. I didn't set it up yet, just installed it. Maybe its setup sequence is misbehaving.

Anyway, this may be a false alarm for you, in which case I apologize. I will update if there is anything relevant.

Here is the requested BC output:

```
1459146064889   tabgroupsbtn    ERROR   getGroupItems: win.TabView is undefined Log.jsm:751:0
1459146065399   tabgroupsbtn    ERROR   getGroupItems: win.TabView is undefined Log.jsm:751:0
```

**Comment by char101** [comment]
That is not an error (although it says ERROR). The addon retries loading panorama several times since the addon loading order is undeterministic now that tabgroups has been moved into an addon.

If you want you can paste the whole Browser Console output here and I will see if I can find your problem.

**Comment by seascape** [comment]
I found the issue: KeeFox absolutely shit the bed because it somehow completed its setup event without knowing where KeePass was installed to. No KeePass = KeeFox went on a rampage, breaking the UI. Easily remedied by supplying it a path, thankfully.

Thanks for your help, and sorry again for the false alarm.
