### ISSUE TITLE
Opening a tab group for the first time in session opens new tab instead of last tab open.

### ISSUE THREAD

**Issue by PrototypeNM1** [char101/tabgroupsbtn#18]
When opening a tab group from the tab group bar, if the group has not previously been opened since Firefox started, a new tab is open. This behavior is inconsistent with Tab Groups, which is able to open the last open tab from the group.

**Comment by char101** [comment]
It is by design. The addon tries not to select an unloaded tab. Consistency with Tab Groups is irrelevant, it is two different addon, made by two different person. I made this addon for my need.
