### ISSUE TITLE
List of group not loaded after startup

### ISSUE THREAD

**Issue by Rotozaza** [char101/tabgroupsbtn#7]
Please fix delayed loading of group list, only first interaction (Move to Group) loads list, only then drop-down lists group. Both menu and button. 

Initial name  of drop down of Tab Group Button is 'Tab Group'. There is no 'Move to group' context menu before clicking this once. 

Issue exists since 2 years...

**Comment by char101** [comment]
That's by design; panorama is not designed to be loaded immediately on firefox start. Even the builtin panorama button loads it on demand.

**Comment by Rotozaza** [comment]
Related, same idea other approach: https://www.mozdev.org/bugs/show_bug.cgi?id=25638

**Comment by char101** [comment]
Session data is not related to panorama. This addon does not modify firefox session.

**Comment by Rotozaza** [comment]
I was unclear, it's another approach, to same thing, just FYI. 

Basic need: 
group open pages (tabs) to wherever 
move pages between groups on context menu 
switch fast between groups 

Session manager shows as tab groups what is, closing of tab removes entry. Therefore bookmarks or services as Pocket are cumbersome. 

Why do I fancy a session approach, the group not active isn't loaded to memory, and list is loaded at start-up.
