### ISSUE TITLE
Opening additional New Tab on first switch to a group after startup

### ISSUE THREAD

**Issue by hidavy** [char101/tabgroupsbtn#9]
When I switch to a group for the first time after startup, it automatically opens a New Tab.
Version 0.52.1
Firefox settings: When Firefox starts: "Show my windows and tabs from last time"; "Don't load tabs until selected" enabled.

**Comment by char101** [comment]
That is by design: "don't load tabs until selected", so it opens a new tab until you select an unloaded tab.
